import {
  ARTICLE_QUERYResult,
  Content,
  EVENT_QUERYResult,
} from "../sanity.types";

/***
 * This file is a custom type definition for the Sanity schema.
 * It is used to define the types of the custom content fields in the Sanity schema.
 * The types defined here are used in the frontend to render the custom content fields.
 * Update custom types accordingly after running sanity typegen. The custom types are not generated by the typegen command.
 * Will only need to be updated if the schema changes for the extended types here.
 * The custom types are named with the prefix "Custom_" or "Custom" to avoid conflicts with the generated types and easier lookup.
 * Import the custom types through sanity/types in the frontend.
 */

export type CustomContent = Omit<
  NonNullable<Content>,
  "video" & {
    video: CustomVideo;
  }
>;

type TagText = {
  subtitle: string;
  _key: string;
}[];

export type Custom_ARTICLE_QUERYResult = Omit<
  NonNullable<ARTICLE_QUERYResult>,
  "video" | "text" | "tagTexts"
> & {
  video: CustomVideo;
  text: CustomContent;
  tagTexts: TagText;
};

export type Custom_EVENT_QUERYResult = Omit<
  NonNullable<EVENT_QUERYResult>,
  "video" | "text"
> & {
  video: CustomVideo;
  text: CustomContent;
};

type CustomVideo = {
  title: string;
  muxVideo: {
    asset: {
      playbackId: string;
    };
  };
};

type ArrayElement<T> = T extends Array<infer E> ? E : never;

type RoleGroupsArray = NonNullable<EVENT_QUERYResult>["roleGroups"];
// Hent arraytypen for elementet
export type QueriedRoleGroup = ArrayElement<RoleGroupsArray>; // Den her som prop til <RoleGroup />
