name: Post to a Slack channel
run-name: update slack
on:
  pull_request:
    types: [opened, review_requested, closed]
    branches:
      - slack-bot

jobs:
  sendMessageOpened:
    runs-on: ubuntu-latest
    steps:
      - name: Post to a Slack channel
        id: slack
        if: "${{github.event.action == 'opened'}}"
        uses: slackapi/slack-github-action@v1.26.0
        with:
          channel-id: "C079LPG4YJE"
          slack-message: "📂 ${{ github.event.pull_request.user.login}} \nopened new PR: ${{ github.event.pull_request.title }} \n${{ github.event.pull_request.html_url }} "
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}

  sendMessageReview:
    runs-on: ubuntu-latest
    steps:
      - name: Post to a Slack channel
        id: slack
        if: "${{github.event.action == 'review_requested'}}"
        uses: slackapi/slack-github-action@v1.26.0
        with:
          channel-id: "C079LPG4YJE"
          slack-message: "🔍 ${{ github.event.pull_request.title }} \nRequested review from:  ${{ github.event.pull_request.requested_reviewers[0].login|| 'N/A'}}  \nLink:${{ github.event.pull_request._links.html.href}}"
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}

  sendMessageClosed:
    runs-on: ubuntu-latest
    steps:
      - name: Post to a Slack channel
        id: slack
        if: "${{github.event.pull_request.merged == true}}"
        uses: slackapi/slack-github-action@v1.26.0
        with:
          channel-id: "C079LPG4YJE"
          slack-message: "⭐️ ${{ github.event.pull_request.title }} \nPR status: ${{ github.event.action == 'closed' && github.event.pull_request.merged == true && 'merged' || 'not merged' }} \nLink: ${{ github.event.pull_request._links.html.href}}"
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
